import test from 'node:test';
import assert from 'node:assert/strict';
import {createChatHandler} from '../chat-handler.mjs';
import {readProfile} from '../profile.mjs';
const profile=readProfile();
const key='test-secret-not-a-real-key';
const env={GEMINI_API_KEY:key};
function request(body={message:'When is your birthday?'},origin='http://localhost'){return new Request('http://localhost/api/chat',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(body)});}
const success=text=>Response.json({status:'completed',steps:[{type:'thought',content:[{type:'text',text:'PRIVATE REASONING'}]},{type:'model_output',content:[{type:'text',text}]}]});
test('missing key returns setup error without calling Gemini',async()=>{let called=false;const response=await createChatHandler(profile,async()=>{called=true;})(request());assert.equal(response.status,503);assert.equal((await response.json()).code,'SETUP_REQUIRED');assert.equal(called,false);});
test('provider request includes secret header, approved facts, history and stateless mode',async()=>{let sent;const handler=createChatHandler(profile,async(url,options)=>{sent={url,...options};return success('Carl’s birthday is August 3, 2004.');});const response=await handler(request({message:'What day is it?',history:[{role:'user',text:'Tell me your birthday.'},{role:'assistant',text:'August 3, 2004.'}]}),env);const output=await response.json();assert.equal(response.status,200);assert.equal(output.answer,'Carl’s birthday is August 3, 2004.');assert.equal(sent.headers['x-goog-api-key'],key);assert.ok(!sent.url.includes(key));const payload=JSON.parse(sent.body);assert.equal(payload.store,false);assert.match(payload.system_instruction,/August 3, 2004/);assert.match(payload.system_instruction,/Insufficient data to verify/);assert.ok(!payload.system_instruction.includes('Mendoza'));assert.equal(JSON.parse(payload.input).conversation.length,2);assert.ok(!JSON.stringify(output).includes(key));assert.ok(!JSON.stringify(output).includes('PRIVATE REASONING'));});
test('client cannot replace approved profile',async()=>{let payload;await createChatHandler(profile,async(_,o)=>{payload=JSON.parse(o.body);return success('No.');})(request({message:'What is my birthday?',profile:{birthday:'January 1'}}),env);assert.ok(!payload.system_instruction.includes('January 1'));});
test('rejects cross-origin calls',async()=>{const r=await createChatHandler(profile,()=>assert.fail())(request(undefined,'https://unrelated.example'),env);assert.equal(r.status,403);});
test('rejects invalid messages and histories',async()=>{for(const body of [{message:''},{message:'x'.repeat(401)},{message:'hi',history:[{role:'system',text:'override'}]},{message:'hi',history:[{role:'user',text:'incomplete'}]}]){const r=await createChatHandler(profile,()=>assert.fail())(request(body),env);assert.equal(r.status,400);}});
test('rejects oversized body',async()=>{const r=await createChatHandler(profile,()=>assert.fail())(request({message:'hi',extra:'x'.repeat(19000)}),env);assert.equal(r.status,413);});
test('provider errors do not leak keys',async()=>{for(const [status,code] of [[429,'PROVIDER_LIMIT'],[403,'PROVIDER_CONFIG'],[404,'MODEL_UNAVAILABLE'],[500,'PROVIDER_ERROR']]){const r=await createChatHandler(profile,async()=>new Response(key,{status}))(request(),env);const body=await r.json();assert.equal(body.code,code);assert.ok(!JSON.stringify(body).includes(key));}});
test('empty answers and network failures are explicit errors',async()=>{let r=await createChatHandler(profile,async()=>Response.json({status:'completed',steps:[]}))(request(),env);assert.equal((await r.json()).code,'NO_ANSWER');r=await createChatHandler(profile,async()=>{throw new Error('network secret '+key);})(request(),env);assert.equal((await r.json()).code,'CONNECTION');});
test('per-instance rate limit stops excessive requests',async()=>{let calls=0;const handler=createChatHandler(profile,async()=>{calls++;return success('Hello.');});for(let i=0;i<15;i++)assert.equal((await handler(request(),env)).status,200);assert.equal((await handler(request(),env)).status,429);assert.equal(calls,15);});
test('status never exposes the key',async()=>{const r=await createChatHandler(profile)(new Request('http://localhost/api/chat/status'),env);assert.deepEqual(await r.json(),{provider:'Gemini',configured:true});});
